export type KeyboardKeys = typeof keyboardKeys;
export const keyboardKeys = [
  // top row
  { note: "D#2", keymap: "Digit1" },
  { note: "E2", keymap: "KeyQ" },
  { note: "F2", keymap: "KeyW" },
  { note: "F#2", keymap: "Digit3" },
  { note: "G2", keymap: "KeyE" },
  { note: "G#2", keymap: "Digit4" },
  { note: "A2", keymap: "KeyR" },
  { note: "A#2", keymap: "Digit5" },
  { note: "B2", keymap: "KeyT" },
  { note: "C3", keymap: "KeyY" },
  { note: "C#3", keymap: "Digit7" },
  { note: "D3", keymap: "KeyU" },
  { note: "D#3", keymap: "Digit8" },
  { note: "E3", keymap: "KeyI" },
  { note: "F3", keymap: "KeyO" },
  { note: "F#3", keymap: "Digit0" },
  { note: "G3", keymap: "KeyP" },
  { note: "G#3", keymap: "Minus" },
  { note: "A3", keymap: "BracketLeft" },
  { note: "A#3", keymap: "Equal" },
  { note: "B3", keymap: "BracketRight" },
  // btm row
  { note: "C4", keymap: "KeyZ" },
  { note: "C#4", keymap: "KeyS" },
  { note: "D4", keymap: "KeyX" },
  { note: "D#4", keymap: "KeyD" },
  { note: "E4", keymap: "KeyC" },
  { note: "F4", keymap: "KeyV" },
  { note: "F#4", keymap: "KeyG" },
  { note: "G4", keymap: "KeyB" },
  { note: "G#4", keymap: "KeyH" },
  { note: "A4", keymap: "KeyN" },
  { note: "A#4", keymap: "KeyJ" },
  { note: "B4", keymap: "KeyM" },
  { note: "C5", keymap: "Comma" },
  { note: "C#5", keymap: "KeyL" },
  { note: "D5", keymap: "Period" },
  { note: "D#5", keymap: "Semicolon" },
  { note: "E5", keymap: "Slash" },
  // notes with no keys
  { note: "F5" },
  { note: "F#5" },
  { note: "G5" },
  { note: "G#5" },
  { note: "A5" },
  { note: "A#5" },
  { note: "B5" },
  { note: "C6" },
  { note: "C#6" },
];
